# To do 3 - Ho spostato le variabili in un file separato per una migliore organizzazione e riutilizzabilità.
docker_key_dir: /etc/apt/keyrings
docker_key_url: https://download.docker.com/linux/ubuntu/gpg