---
- name: Crea utente tester
  ansible.builtin.user:
    name: "{{ test_name }}"
    shell: "{{ test_shell }}"
    create_home: true
    state: present

- name: Aggiungi chiave pubblica ad authorized_keys
  ansible.posix.authorized_key:
    user: "{{ test_name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: Aggiungi chiave pubblica ad authorized_keys di root
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
