Vagrant.configure("2") do |config|

           # Proxy-dev  
  config.vm.define "proxy-dev" do |vm|
    vm.vm.box = "ubuntu/jammy64"
    vm.vm.hostname = "proxy-dev"
    vm.vm.network "private_network", ip: "192.168.3.60"

    
      vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

           # Proxy-test  
  config.vm.define "proxy-test" do |vm|
    vm.vm.box = "ubuntu/jammy64"
    vm.vm.hostname = "proxy-test"
    vm.vm.network "private_network", ip: "192.168.3.61"

    
      vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

           # Proxy-prod  
  config.vm.define "proxy-prod" do |vm|
    vm.vm.box = "ubuntu/jammy64"
    vm.vm.hostname = "proxy-prod"
    vm.vm.network "private_network", ip: "192.168.3.62"

    
      vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end
